disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
included: 
  - ProjectTemplate/Application
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Docs
  - Tests
  - UITests
  - Screenshots
  - Frameworks
  - Scripts
  - Carthage
  - Pods
  - Packages
file_length:
  warning: 500
  error: 1200
line_length: 150